"""Cross-agent wire protocol — signed message models for IOU-based capability trades.

All signing uses canonical JSON: json.dumps with sort_keys=True and compact
separators. The middleware handles outer HTTP-level Ed25519 signatures. The
EscrowProof and TransactionReceipt carry their own embedded signatures so
either party can independently verify the commitment at any future time.
"""

from __future__ import annotations

import json
from enum import Enum
from typing import Any

from pydantic import BaseModel


def canonical_json(data: dict[str, Any]) -> bytes:
    """Produce deterministic JSON bytes for signing (sorted keys, no spaces)."""
    return json.dumps(data, separators=(",", ":"), sort_keys=True).encode("utf-8")


# ── Signed proof models ─────────────────────────────────────────────────────


class EscrowProof(BaseModel):
    """Buyer's signed proof of locked escrow funds.

    Sent to seller inside FundNotification so the seller can verify
    funds are committed before executing the capability.
    """

    tx_id: str
    escrow_id: str
    buyer_aid: str
    seller_aid: str
    amount: int
    timestamp: str  # ISO-8601 UTC, e.g. "2026-03-29T12:00:00Z"
    signature: str  # base64-encoded Ed25519 sig over signable_bytes()

    def signable_bytes(self) -> bytes:
        """Canonical bytes that were / should be signed (excludes signature)."""
        return canonical_json(
            {
                "tx_id": self.tx_id,
                "escrow_id": self.escrow_id,
                "buyer_aid": self.buyer_aid,
                "seller_aid": self.seller_aid,
                "amount": self.amount,
                "timestamp": self.timestamp,
            }
        )


class TransactionReceipt(BaseModel):
    """Buyer's signed confirmation of delivery.

    Sent to seller inside ConfirmNotification. The seller stores the
    receipt_hash in cross_agent_debts as proof. The Task 4 settlement
    service will consume these receipts to convert IOUs into real balance.
    """

    tx_id: str
    escrow_id: str
    buyer_aid: str
    seller_aid: str
    amount: int
    result_hash: str
    timestamp: str  # ISO-8601 UTC
    signature: str  # base64-encoded Ed25519 sig over signable_bytes()

    def signable_bytes(self) -> bytes:
        """Canonical bytes that were / should be signed (excludes signature)."""
        return canonical_json(
            {
                "tx_id": self.tx_id,
                "escrow_id": self.escrow_id,
                "buyer_aid": self.buyer_aid,
                "seller_aid": self.seller_aid,
                "amount": self.amount,
                "result_hash": self.result_hash,
                "timestamp": self.timestamp,
            }
        )


# ── Inbox message types ─────────────────────────────────────────────────────


class InboxMessageType(str, Enum):
    CAPABILITY_REQUEST = "CAPABILITY_REQUEST"
    FUND_NOTIFICATION = "FUND_NOTIFICATION"
    CONFIRM_NOTIFICATION = "CONFIRM_NOTIFICATION"


class InboxMessage(BaseModel):
    """Outer typed wrapper for all inbox messages."""

    message_type: InboxMessageType
    payload: dict[str, Any]


# ── Per-message-type payload models ────────────────────────────────────────


class CapabilityRequest(BaseModel):
    """Buyer requests a capability quote from seller.

    The tx_id is pre-generated by the buyer and shared so both sides use the
    same transaction identifier throughout the lifecycle.
    """

    tx_id: str
    buyer_aid: str
    capability_id: str
    buyer_url: str  # buyer's HTTP base URL (for future reverse callbacks)


class QuoteResponse(BaseModel):
    """Seller's synchronous quote response."""

    tx_id: str
    price: int
    seller_aid: str
    capability_name: str = ""


class FundNotification(BaseModel):
    """Buyer notifies seller that escrow is locked and provides proof."""

    tx_id: str
    escrow_proof: EscrowProof


class DeliveryResult(BaseModel):
    """Seller's synchronous delivery response."""

    tx_id: str
    result_hash: str
    seller_aid: str


class ConfirmNotification(BaseModel):
    """Buyer confirms delivery and provides a signed receipt for IOU recording."""

    tx_id: str
    receipt: TransactionReceipt


__all__ = [
    "canonical_json",
    "EscrowProof",
    "TransactionReceipt",
    "InboxMessageType",
    "InboxMessage",
    "CapabilityRequest",
    "QuoteResponse",
    "FundNotification",
    "DeliveryResult",
    "ConfirmNotification",
]
